# Generated by Django 3.0.6 on 2020-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vote_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votename', models.CharField(max_length=200)),
                ('votecontent', models.CharField(max_length=2000)),
                ('voteintro', models.CharField(max_length=200)),
                ('votetype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vote_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteid', models.CharField(max_length=200)),
                ('sno', models.CharField(max_length=2000)),
                ('sname', models.CharField(max_length=200)),
                ('tno', models.CharField(max_length=20)),
            ],
        ),
    ]
