# Generated by Django 3.0.6 on 2020-11-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_vote_result_stno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_result',
            name='stno',
            field=models.CharField(max_length=200),
        ),
    ]
