# Generated by Django 3.0.6 on 2020-11-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20201108_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_result',
            name='stno',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
